//
// Created by vanes on 11/22/2021.
//

#ifndef MAIN_CPP_CARDNAME_H
#define MAIN_CPP_CARDNAME_H

enum CardName {
    SHUFFLE_1, SHUFFLE_2, SHUFFLE_3,
    SEE_THE_FUTURE_1, SEE_THE_FUTURE_2, SEE_THE_FUTURE_3,
    STEAL_A_CARD_1, STEAL_A_CARD_2, STEAL_A_CARD_3,
    DRAW_FROM_BOTTOM_1, DRAW_FROM_BOTTOM_2, DRAW_FROM_BOTTOM_3,
    SKIP_1, SKIP_2, SKIP_3, SKIP_4, SKIP_5,
    DOUBLE_SLAP_1, DOUBLE_SLAP_2,
    DEFUSE_1, DEFUSE_2, DEFUSE_3,
    DICKENS,
};
#endif //MAIN_CPP_CARDNAME_H
