//
// Created by vanes on 11/23/2021.
//

#ifndef BUTTON_H_GAMESCREENNAME_H
#define BUTTON_H_GAMESCREENNAME_H

enum GameScreenName
{
    SPLASH_SCREEN, ABOUT_SCREEN, INSTRUCTIONS_SCREEN, PLAYER_NAME_SCREEN,
    GAME_SCREEN,

    SEE_THE_FUTURE_SCREEN,

    END_SCREEN_WIN, END_SCREEN_LOSE,

    LAST_GAME_SCREEN
};
#endif //BUTTON_H_GAMESCREENNAME_H
