//
// Created by vanes on 11/18/2021.
//

#ifndef MAIN_CPP_STATENAME_H
#define MAIN_CPP_STATENAME_H

enum StateName {
    ROLLOVER, CLICK, ROLLEDOVER_ONCE, CLICKED_ONCE,

    RIGHT_CLICK, R_CLICKED_ONCE,

    HIDDEN,

    DRAW_CARD,

    GAME_START,

    PLAYER_TURN, PLAYER_TURN_INTRO, SHOWED_INTRO_ONCE,

    FIRST_TURN, FIRST_TURN_INTRO, SHOWED_FIRST_TURN_ONCE,

    SEE_THE_FUTURE_OVERLAY,

    DEFUSE_DICKENS_OVERLAY,

    HIDE_DICKENS_OVERLAY,

    HIDE_DICKENS_CARD, HIDE_DICKENS_EVENT, HID_DICKENS_ONCE,

    CHARLES_STEALS, CHARLES_STEALS_EVENT, CHARLES_STOLE_ONCE,

    CHARLES_DREW_EXP_DICKENS, CHARLES_DICKENS_EXP_EVENT, SHOWED_CHARLES_DICKENS_EXP_EVENT_ONCE,

    CHARLES_HIDES_DICKENS_CARD, CHARLES_HIDES_DICKENS_EVENT, CHARLES_HID_DICKENS_ONCE,

    TAUNTS, TAUNTS_INTRO, SHOWED_TAUNTS_INTRO_ONCE,

    SHUFFLE_CARDS, SHUFFLE_EVENT, SHUFFLED_ONCE,

    PLAYER_WINS, PLAYER_LOSES,

    PLAY_AGAIN_WIN, PLAY_AGAIN_LOSE,

    IN_PLAYER_HAND, IN_DECK, IN_DISCARD_PILE, IN_OPPONENT_HAND,

    FACE_VISIBLE,

    SELECT,

    LAST
};
#endif //MAIN_CPP_STATENAME_H
